import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:stilp_v1/src/core/models/project_document.dart';
import 'package:stilp_v1/src/features/export_preview/pdf/project_pdf_builder.dart';
import 'package:stilp_v1/src/features/export_preview/state/pdf_export_controller.dart';

void main() {
  test('export fails cleanly when there is no active project', () async {
    final controller = PdfExportController(
      builder: _FakeProjectPdfBuilder(),
      gateway: _FakePdfExportGateway(),
      now: () => DateTime.utc(2026, 4, 25, 9, 0),
    );

    await controller.exportActiveProject(null);

    expect(controller.state.isLoading, isFalse);
    expect(controller.state.errorMessage, 'Ingen aktivt projekt fundet.');
    expect(controller.state.successMessage, isNull);
  });

  test('export succeeds for active project', () async {
    final gateway = _FakePdfExportGateway();
    final controller = PdfExportController(
      builder: _FakeProjectPdfBuilder(),
      gateway: gateway,
      now: () => DateTime.utc(2026, 4, 25, 9, 0),
    );

    final project = ProjectDocument.empty(
      projectId: 'project-1',
      taskType: 'Stillads',
      now: DateTime.utc(2026, 4, 25, 8, 0),
    );

    await controller.exportActiveProject(project);

    expect(controller.state.successMessage, 'PDF genereret.');
    expect(controller.state.errorMessage, isNull);
    expect(gateway.lastFilename, 'stilp_project-1_20260425_0900.pdf');
  });

  test('export passes generated bytes to gateway abstraction', () async {
    final gateway = _FakePdfExportGateway();
    final expectedBytes = Uint8List.fromList([1, 2, 3, 4]);
    final controller = PdfExportController(
      builder: _FakeProjectPdfBuilder(result: expectedBytes),
      gateway: gateway,
      now: () => DateTime.utc(2026, 4, 25, 9, 0),
    );

    final project = ProjectDocument.empty(
      projectId: 'project-abc',
      taskType: 'Stillads',
      now: DateTime.utc(2026, 4, 25, 8, 0),
    );

    await controller.exportActiveProject(project);

    expect(gateway.lastBytes, expectedBytes);
  });

  test('filename is sanitized and stable', () {
    final filename = buildPdfFilename(' project id/with spaces ', DateTime.utc(2026, 4, 25, 13, 7));

    expect(filename, 'stilp_project_id_with_spaces_20260425_1307.pdf');
  });
}

class _FakeProjectPdfBuilder extends ProjectPdfBuilder {
  _FakeProjectPdfBuilder({Uint8List? result}) : _result = result ?? Uint8List.fromList([9, 9]);

  final Uint8List _result;

  @override
  Future<Uint8List> build(ProjectDocument project) async {
    return _result;
  }
}

class _FakePdfExportGateway implements PdfExportGateway {
  Uint8List? lastBytes;
  String? lastFilename;

  @override
  Future<void> openPdf({required Uint8List bytes, required String filename}) async {
    lastBytes = bytes;
    lastFilename = filename;
  }
}
