import 'package:flutter_test/flutter_test.dart';
import 'package:stilp_v1/src/core/models/facade_document.dart';
import 'package:stilp_v1/src/core/models/facade_marker.dart';
import 'package:stilp_v1/src/core/models/facade_section.dart';
import 'package:stilp_v1/src/core/models/facade_storey.dart';
import 'package:stilp_v1/src/core/models/manual_packing_list_item.dart';
import 'package:stilp_v1/src/core/models/plan_side.dart';
import 'package:stilp_v1/src/core/models/plan_view_data.dart';
import 'package:stilp_v1/src/core/models/project_document.dart';
import 'package:stilp_v1/src/features/export_preview/image/project_image_builder.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  test('generating bytes returns non-empty bytes for populated project', () async {
    final builder = ProjectImageBuilder();

    final bytes = await builder.build(_buildProject());

    expect(bytes, isNotEmpty);
  });

  test('generated bytes have PNG signature', () async {
    final builder = ProjectImageBuilder();

    final bytes = await builder.build(_buildProject());

    expect(bytes.length, greaterThanOrEqualTo(4));
    expect(bytes[0], 0x89);
    expect(bytes[1], 0x50);
    expect(bytes[2], 0x4E);
    expect(bytes[3], 0x47);
  });

  test('empty project sections do not crash builder', () async {
    final builder = ProjectImageBuilder();

    final bytes = await builder.build(
      ProjectDocument.empty(
        projectId: 'empty',
        taskType: 'Stillads',
        now: DateTime.utc(2026, 4, 25, 8, 0),
      ),
    );

    expect(bytes, isNotEmpty);
  });

  test('notes section handles notes and empty notes', () async {
    final builder = ProjectImageBuilder();

    final withNotes = await builder.build(
      _buildProject().copyWith(notes: 'Bemærkning med tekst.'),
    );
    final withoutNotes = await builder.build(
      _buildProject().copyWith(notes: '   '),
    );

    expect(withNotes, isNotEmpty);
    expect(withoutNotes, isNotEmpty);
  });

  test('many facades do not crash and produce bytes', () async {
    final builder = ProjectImageBuilder();
    final facades = List.generate(60, (index) {
      return FacadeDocument.emptyForSide(
        sideId: 'side-$index',
        label: 'Facade $index',
      ).copyWith(
        edgeLengthMm: 12000 + index,
        sideType: index.isEven ? PlanSideType.langside : PlanSideType.gavl,
      );
    });

    final bytes = await builder.build(_buildProject().copyWith(facades: facades));

    expect(bytes, isNotEmpty);
  });

  test('many packing rows do not crash and produce bytes', () async {
    final builder = ProjectImageBuilder();
    final items = List.generate(
      120,
      (index) => ManualPackingListItem(
        id: 'row-$index',
        text: 'Linje $index',
        quantity: index.toDouble(),
        unit: 'stk',
      ),
    );

    final bytes = await builder.build(_buildProject().copyWith(manualPackingList: items));

    expect(bytes, isNotEmpty);
  });

  test('throws clear exception when calculated image height exceeds max', () async {
    final builder = ProjectImageBuilder();
    final oversizedNotes = List.filled(7000, 'Lang note linje for eksport').join('\n');

    expect(
      () => builder.build(_buildProject().copyWith(notes: oversizedNotes)),
      throwsA(isA<ImageExportTooLargeException>()),
    );
  });

  test('standing height and top zone data do not crash builder', () async {
    final builder = ProjectImageBuilder();

    final bytes = await builder.build(_buildProject());

    expect(bytes, isNotEmpty);
  });

  test('marker counts do not crash builder', () async {
    final builder = ProjectImageBuilder();
    final facades = [
      _buildProject().facades.first.copyWith(
            markers: List.generate(
              50,
              (index) => FacadeMarker(
                id: 'marker-$index',
                type: FacadeMarkerType.console,
                sectionIndex: 0,
                storeyIndex: 0,
              ),
            ),
          ),
    ];

    final bytes = await builder.build(_buildProject().copyWith(facades: facades));

    expect(bytes, isNotEmpty);
  });
}

ProjectDocument _buildProject() {
  return ProjectDocument.empty(
    projectId: 'project-image-builder',
    taskType: 'Stillads',
    now: DateTime.utc(2026, 4, 25, 8, 0),
  ).copyWith(
    notes: 'Adgang fra gårdside.',
    planView: PlanViewData(
      enabled: true,
      nodes: [
        PlanViewNode(id: 'n1', x: 0, y: 0),
        PlanViewNode(id: 'n2', x: 100, y: 0),
      ],
      edges: [
        PlanViewEdge(
          id: 'e1',
          fromNodeId: 'n1',
          toNodeId: 'n2',
          lengthMm: 12500,
          sideType: PlanSideType.langside,
        ),
      ],
    ),
    facades: const [
      FacadeDocument(
        sideId: 'e1',
        label: 'Facade A',
        planEdgeId: 'e1',
        sideOrder: 0,
        edgeLengthMm: 18000,
        sideType: PlanSideType.gavl,
        eavesHeightMm: null,
        ridgeHeightMm: null,
        standingHeightM: 5.5,
        topZoneM: 1.0,
        sections: [
          FacadeSection(id: 's1', widthM: 3.0),
          FacadeSection(id: 's2', widthM: 3.0),
        ],
        storeys: [
          FacadeStorey(id: 'st1', heightM: 2.0, kind: FacadeStoreyKind.main),
          FacadeStorey(id: 'st2', heightM: 2.0, kind: FacadeStoreyKind.main),
        ],
        markers: [
          FacadeMarker(
            id: 'm1',
            type: FacadeMarkerType.console,
            sectionIndex: 0,
            storeyIndex: 0,
          ),
        ],
      ),
    ],
    manualPackingList: const [
      ManualPackingListItem(id: 'p1', text: 'Rammer', quantity: 40, unit: 'stk'),
    ],
  );
}
